version: 0.2
phases:
  install:
    commands:
      - sudo apt-get install jq
      - npm install
      - npm install -g serverless
  pre_build:
    commands:
        # sls deploy will need aws provider credentials.
      - temp_role=$(aws sts assume-role --role-arn $CodeBuildRoleARN --role-session-name $RoleSessionName)
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
  build:
    commands:
      - serverless deploy
